{{- if .Values.rbac.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "workload-fixer.fullname" . }}
  labels:
    {{- include "workload-fixer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "workload-fixer.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "workload-fixer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
