{{- if not .Values.rbac.clusterScoped }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "workload-fixer.fullname" . }}
  namespace: {{ include "workload-fixer.watchNamespace" . }}
  labels:
    {{- include "workload-fixer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
{{- end }}
